### ISSUE TITLE
Home page Banner and status bar

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#110]
![image-1](https://user-images.githubusercontent.com/5376514/38438610-d60f1f66-398f-11e8-95d0-642e59e4c1c0.jpg)

The status bar is showing black text on iOS. Can you look into fixing this?

Also, the HomePage's LCSC banner (like on the Login page) is missing, apparently only on iOS. Please look into this.

**Comment by dneverson** [comment]
Talked with Nina today, everything looks to be in order
