### ISSUE TITLE
Home Page Buttons

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#147]
The  home page buttons need a redesign. Please make them look similar to the buttons to the links to view more details on the home lcsc page (www.lcsc.edu)

Ex: see the text links for News and Events (more news headlines ->)

Use the Ionic Framework's buttons
<button ion-button clear ...> To get this working, and use CSS to adjust. Don't make this from scratch.

**Comment by mjensenlcsc** [comment]
Completed in #161
