### ISSUE TITLE
Login Page - Loading Controller

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#150]
When logging in, it's hard to tell if the user hit the login button or not. Because of the wait between logging in and going to the home page, users may be confused if something is happening or not. 

Please add a loading animation to this button tap event. Use Ionic's [loading controller](https://ionicframework.com/docs/api/components/loading/LoadingController/)

**Comment by AustinHaugerud** [comment]
The class-schedule-enhancement branch uses the loading controller for both the login process and when schedule data is pending. I'll be making a pull request to master soon.
