### ISSUE TITLE
Splash Screen and App Icon images too small

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#151]
Please adjust images to the proper dimensions at very high quality (no compression!)

icon.png -> 1024x1024

splash.png -> 2732x2732

**Comment by luvjOi** [comment]
I’m still getting it all done. I’ve got the app icon stuff ready but I still need to do the splash screen stuff. I should be able to push it later today, hopefully before class

**Comment by clblamires** [comment]
icon and Splash screens are done. Whoever builds the apps, make sure to run the command `ionic cordova resources` to generate all icons and splashes.
