### ISSUE TITLE
Free tutoring from home page

### ISSUE THREAD

**Issue by Jesse-McDonald** [lcsc-capstone/lcsc-ionic-app#157]
To get to the free tutoring page you have to click the link on the home page and then click the back button or the page will not open

**Comment by ninamariepeterson** [comment]
This is also replicated on my iPhone.  It wasn't doing this at 10:30am when class started.

**Comment by mjensenlcsc** [comment]
There is some part of the form causing it. Removing the form tag OR removing all data from inside the form tag fixes the issue. It is some combination of the two.
