### ISSUE TITLE
Update config.xml

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#160]
Since the project is very near completion, the config.xml file needs to be updated.

Lines 2, 3, 4, and 5 in particular need modification. Those include the app's name, description, and author information. The id "io,ionic.starter" is the reverse-domain identifier and needs to be changed.

Specifics on what goes into config.xml can be found on the [Cordova documentation](https://cordova.apache.org/docs/en/latest/config_ref/)

**Comment by luvjOi** [comment]
I found the file in my copy, would the author be the school information?

**Comment by dneverson** [comment]
what email address are you wanting to use?

**Comment by ninamariepeterson** [comment]
Please use the ns-appstore@lcmail.lcsc.edu<mailto:ns-appstore@lcmail.lcsc.edu> email. I will verify the email address tomorrow if you don’t have it.

Thanks,
Nina

Sent from my iPhone

On Apr 19, 2018, at 10:13 PM, Derry Everson <notifications@github.com<mailto:notifications@github.com>> wrote:


what email address are you wanting to use?

**Comment by dneverson** [comment]
Changing <widget version="0.0.1"> to <widget version="1.0.1">causes build issues, will investigate further in the morning. all other changes are in calendar-and-events branch now.
