### ISSUE TITLE
Need more info on class schedules.

### ISSUE THREAD

**Issue by CJClawson** [lcsc-capstone/lcsc-ionic-app#192]
Notice that in the screenshot, CITPT413 and CITPT294B are online classes and therefore have no location or schedule.

Info we should add to display:
- [ ] Name of class
- [ ] General info for online classes
- [ ] Professor

![screenshot_20180423-162612_lcsc](https://user-images.githubusercontent.com/35786008/39158157-47753998-4713-11e8-8605-5db1856a2c33.jpg)

**Comment by AustinHaugerud** [comment]
I've changed the class schedule component to detail such information.
