### ISSUE TITLE
Student Planning vs Warrior Web

### ISSUE THREAD

**Issue by ninamariepeterson** [lcsc-capstone/lcsc-ionic-app#195]
Please change the Warrior Web link to student planning.  This should be more mobile friendly.

**Comment by AustinHaugerud** [comment]
How should guest mode handle this?

**Comment by clblamires** [comment]
That's a good question. I think if the link just opened Student Planning without auto-fill for the credentials, that would suffice

**Comment by AustinHaugerud** [comment]
Alrighty, will get on that soon.

**Comment by ninamariepeterson** [comment]
Austin please have it open to the home page on student planning.
Thanks

Sent from my iPhone

On Apr 25, 2018, at 1:30 PM, Austin J. <notifications@github.com<mailto:notifications@github.com>> wrote:


Alrighty, will get on that soon.

**Comment by AustinHaugerud** [comment]
Implemented.
