### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ninamariepeterson** [lcsc-capstone/lcsc-ionic-app#202]
It is pulling all events.  It should just pull a year from the current day.

**Comment by mjensenlcsc** [comment]
As far as I see, the last event that is pulled for me is April 18, which would be the last one inside a year timeframe.

**Comment by ninamariepeterson** [comment]
Does it have a spinning wheel on the bottom?

**Comment by ninamariepeterson** [comment]
Can you select the arrow to filter?
