### ISSUE TITLE
Ion-header bar looks weird on iOS

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#24]
[https://user-images.githubusercontent.com/5376514/36703242-9c04dd0e-1b0f-11e8-99f3-4014d7eae5c4.jpg](https://user-images.githubusercontent.com/5376514/36703242-9c04dd0e-1b0f-11e8-99f3-4014d7eae5c4.jpg)
Header bar at the very top of the app is off for iOS users. Please test on iOS devices to see

**Comment by nicdford** [comment]
fixed with https://github.com/lcsc-capstone/lcsc-ionic-app/commit/e4b43ffe947ee7ff28a604b340ae01be574211ba
