### ISSUE TITLE
Develop user workflow for logging in

### ISSUE THREAD

**Issue by nicdford** [lcsc-capstone/lcsc-ionic-app#32]
@austinglarson, can you migrate the same login form you put on the homepage to the "your profile" page? The "your profile" page will not become a "Sign In" link. If you haven't looked, Boise States "my Boise state" app does a good job of reflecting what we'd like to see.

**Comment by austinglarson** [comment]
Yeah, I could do that.

**Comment by nicdford** [comment]
Fixed with #36
