### ISSUE TITLE
"Dont have account" text covers login fields with some keyboards

### ISSUE THREAD

**Issue by Jesse-McDonald** [lcsc-capstone/lcsc-ionic-app#35]
when some keyboards pop up to enter username and password the "Dont have account" text moves to cover the password field

**Comment by clblamires** [comment]
I might suggest not centering the content on the page, and moving up to the top. That way users on small or large phones/tablets won't see this issue.

**Comment by dneverson** [comment]
Is this still an issue? can anyone confirm.

**Comment by austinglarson** [comment]
This should all be good now.
