### ISSUE TITLE
Fixing click events on the sidemenu

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#45]
The side menu (seen in /src/app/app.html) is using on-click events for some reason. Not sure if the Ionic Creator set that up, but it's technically incorrect.

Please change all references of on-click to either (click) to (tap)

Ex: (tap)="goToHome( )" and (tap)="goToNews( )"

**Comment by austinglarson** [comment]
I went through this and changed them. I'll be posting an update soon.
