### ISSUE TITLE
Remove <font> tag!

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#46]
The <font> tag in calendar.html is invalid HTML and may not be supported in future releases of phone OSs. Remove it and use CSS instead.

<ion-icon name="whatever" class="colorClass"></ion-icon>

**Comment by dneverson** [comment]
Yes, all the tags put in place, were put there by me as a "guide line for what it should look like, and the webdev person can go in and fix it up in css" obviously that didn't happen.

**Comment by mjensenlcsc** [comment]
All <font> tags have been removed at this point.
