### ISSUE TITLE
Changes to Initial login page

### ISSUE THREAD

**Issue by nicdford** [lcsc-capstone/lcsc-ionic-app#49]
- [x] don't have an account / view as guest needs to stand out more to make sure users can more quickly enter the app if they don't have an account

- [x] Let's change "Login to WarriorWeb" to say something like "View your Schedule, Login using WarriorWeb Credentials"

- [x] Overall the page needs more clarity and contrast. You could do this a million different ways, but I was playing around with an idea if you wanted to take a look (see below), primarily adding a color overlay on top of the background, to create more contrast (I played around with a white overlay, but black or blue might look good too)

![mock](https://user-images.githubusercontent.com/7292444/37298758-7da48b5a-25de-11e8-9134-453613db384f.jpg)

**Comment by austinglarson** [comment]
Got it, I'll be posting an update pretty soon.

**Comment by nicdford** [comment]
Thanks @austinglarson don't feel like you have to make it look like my mock either, those are just suggestions for ways to increase the contrast.

**Comment by clblamires** [comment]
Can we also do this to the ProfilePage? It's looking very drab, and I honestly can't tell the difference between their functionality. The ProfilePage largely doesn't work.

**Comment by austinglarson** [comment]
Yeah, what is the profile page for?

**Comment by nicdford** [comment]
@austinglarson we talked about changing the profile page to be the "login" page, which may have been lost in the ether.

**Comment by dneverson** [comment]
Changed the "Profile" tab to "Login" also changed the goToLocation to LoginPage from ProfilePage. Both had same functionality and it is easier to maintain 1 page vs. 2. (changes are in calendar-and-events branch)
