### ISSUE TITLE
Menu on Calendar page is positioned to the right

### ISSUE THREAD

**Issue by nicdford** [lcsc-capstone/lcsc-ionic-app#63]
![screen shot 2018-03-14 at 2 58 14 pm](https://user-images.githubusercontent.com/7292444/37433198-2d33d318-2798-11e8-8111-f7c733510f74.png)

Not sure why this is, but the main nav menu icon should be consistent across the entire app in the upper left. The filter option can stay in the right, that is fine, but the hamburger menu icon should be on the left.

**Comment by luvjOi** [comment]
Fixed and made a pull request from the luvjOi-patch-3 branch
