### ISSUE TITLE
Back Button Color

### ISSUE THREAD

**Issue by mjensenlcsc** [lcsc-capstone/lcsc-ionic-app#74]
Any time a page opens that has a back button, the back button is the same color as the title bar.
![calendar](https://user-images.githubusercontent.com/22622828/37540203-5a156fbe-2913-11e8-8f82-f24b2ca10b54.png)

**Comment by dneverson** [comment]
Looks to be fixed? at least on the calendar-and-events branch

**Comment by dneverson** [comment]
Fixed to work like the menu buttons, pushed in calendar-and-events branch
