### ISSUE TITLE
CalendarPage - add to calendar not working

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#79]
Two things on this:
- [x] The add to calendar buttons are not working for either device. See the old app for how this functionality needs to be handled.
- [ ] Links in the calendar event details are not clickable. They should open up in a new device browser tab.

**Comment by mjensenlcsc** [comment]
The adding to calendar is fixed in the calendar-and-events branch.
Making links clickable will need some work.

**Comment by ajwhite2206** [comment]
It works.
