### ISSUE TITLE
SideMenu - change "Profile" to "Login"

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#82]
The word "Profile" in the sidemenu is misleading. Please rename to Login/Logout. Login when the user is not logged in, and Logout when the user is already logged in.

**Comment by dneverson** [comment]
- [ ] Change "Profile" to "Login"
- [ ] Create a variable "guest" in Storage from home.ts and use it in app.html with a:
       < div *ngIf="!guest" > < /div >

**Comment by nicdford** [comment]
Relating to this issue, it looks like the old profile page import didn't get removed when the new login one was created. 

```
[14:57:18]  tslint: C:/Users/Warrior/Documents/GitHub/lcsc-ionic-app/src/app/app.component.ts, line: 8
            All imports are unused.

       L7:  import { ClassSchedulePage } from '../pages/class-schedule/class-schedule';
       L8:  import { ProfilePage } from '../pages/profile/profile';
       L9:  import { NewsPage } from '../pages/news/news';
```

**Comment by dneverson** [comment]
did clean up of useless pages, imports, and variables in calendar-and-events branch awaiting pull to master

**Comment by AustinHaugerud** [comment]
When logged in the users sees "Logout" and when a guest the users sees "Login". Please close this issue.
