### ISSUE TITLE
HomePage - use interlocking LC logo

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#83]
On the HomePage, please remove the word "Home" from the navbar and replace it with a small interlocking LC logo. Logos are found on the communication's page under [Branding](http://www.lcsc.edu/communications/brand/)

**Comment by dneverson** [comment]
What logo are you wanting to use? All the logos are made in mind to having a white background.

**Comment by nicdford** [comment]
The current LCSC site using a white interlocking on a blue background. Here is a link to the file to download: http://www.lcsc.edu/static/images/lcsc-logo--interlocking.svg

**Comment by dneverson** [comment]
Completed and is on the calendar-and-events branch, some tags need to be put into .scss file

**Comment by dneverson** [comment]
moved tags to .scss file

**Comment by nicdford** [comment]
Thank you @dneverson !!!

**Comment by clblamires** [comment]
The ratio for the LC logo's size is slightly off. Set it to 20px wide with 25px high and it should be good.

**Comment by dneverson** [comment]
should be correct size 20px wide with 25px high in calendar-and-events branch now
