### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#85]
- [x] Remove the resource buttons from the home page. They aren't necessary there anymore
- [x] Make the resources work on the side menu

**Comment by mjensenlcsc** [comment]
All links in the sidebar work in the calendar-and-events branch. They open in an in-app-browser so if you are wanting an actual browser then they need some adjusting.

**Comment by dneverson** [comment]
Resource buttons are now removed from the home page.
