### ISSUE TITLE
Social Media links/icons

### ISSUE THREAD

**Issue by clblamires** [lcsc-capstone/lcsc-ionic-app#86]
Please add social media links to the side menu. See LCSC homepage for details.
Please also find out if the school has a SnapChat account. We've been told that we do, but we don't have a link for it yet.

**Comment by mjensenlcsc** [comment]
Snapchat: http://www.lcsc.edu/media/5720159/snapcode.png

**Comment by dneverson** [comment]
@ninamariepeterson did you say that the icons are now showing up on ios?

**Comment by dneverson** [comment]
Icons are in master now, all linking to appropriate places thanks to @luvjOi. Official SnapChat link https://www.snapchat.com/add/lewisclarkstate as found by Will Othank

**Comment by ninamariepeterson** [comment]
Yes, they are showing up on iOS now.

Nina
