### ISSUE TITLE
Change color of status bar

### ISSUE THREAD

**Issue by nicdford** [lcsc-capstone/lcsc-ionic-app#94]
Status bar (battery, clock, etc) should be white to increase the contrast on the blue bar. 

There is a cordova plugin to do this:
https://ionicframework.com/docs/native/status-bar/

@ninamariepeterson is this something one of your CS students should do or should a web student? We just want white text on blue, there should never be black text on a blue background.

**Comment by mjensenlcsc** [comment]
Should be fixed by #113

**Comment by nicdford** [comment]
Thank you @mjensenlcsc
