### ISSUE TITLE
HomePage - Font size of calendar issue

### ISSUE THREAD

**Issue by dneverson** [lcsc-capstone/lcsc-ionic-app#96]
There is an issue with the font size on the homepage for calendar events. In the code it has a label of < h2 > but for some reason is being implemented as < h1 > (lines: 38, 51, and 64) 
![screenshot_20180321-151153](https://user-images.githubusercontent.com/26323801/37740424-e847968a-2d1a-11e8-9d75-ee522855e9a5.png)

**Comment by luvjOi** [comment]
Ok i’ll get on it later tonight, should be an easy fix

**Comment by luvjOi** [comment]
Ok its fixed and pushed

**Comment by dneverson** [comment]
Looks great, thank you @luvj0i
